Lint/UnusedMethodArgument:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/Lambda:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SignalException:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
