dist: bionic
language: ruby
jobs:
  include:
    - name: "Postgres 13"
      rvm: 2.7
      gemfile: Gemfile
      dist: focal
      addons:
        postgresql: "13"
        apt:
          sources:
            - sourceline: deb http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main 13
              key_url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
          packages:
            - postgresql-13
      before_install:
        - echo "shared_preload_libraries = 'pg_stat_statements'" | sudo tee -a /etc/postgresql/13/main/postgresql.conf
        - sudo systemctl restart postgresql@13-main
        - createdb pghero_test
    - name: "Postgres 12"
      rvm: 2.7
      gemfile: Gemfile
      dist: focal
      addons:
        postgresql: "12"
        apt:
          packages:
            - postgresql-12
      before_install:
        - echo "shared_preload_libraries = 'pg_stat_statements'" | sudo tee -a /etc/postgresql/12/main/postgresql.conf
        - sudo systemctl restart postgresql@12-main
        - createdb pghero_test
      env:
        - PGPORT=5433
    - name: "Postgres 11"
      rvm: 2.6
      gemfile: test/gemfiles/activerecord52.gemfile
      addons:
        postgresql: "11"
      before_install:
        - echo "shared_preload_libraries = 'pg_stat_statements'" | sudo tee -a /etc/postgresql/11/main/postgresql.conf
        - sudo systemctl restart postgresql@11-main
        - createdb pghero_test
    - name: "Postgres 10"
      rvm: 2.5
      gemfile: test/gemfiles/activerecord51.gemfile
      addons:
        postgresql: "10"
      before_install:
        - echo "shared_preload_libraries = 'pg_stat_statements'" | sudo tee -a /etc/postgresql/10/main/postgresql.conf
        - sudo systemctl restart postgresql@10-main
        - createdb pghero_test
    - name: "Postgres 9.6"
      rvm: 2.4
      gemfile: test/gemfiles/activerecord50.gemfile
      addons:
        postgresql: "9.6"
      before_install:
        - echo "shared_preload_libraries = 'pg_stat_statements'" | sudo tee -a /etc/postgresql/9.6/main/postgresql.conf
        - sudo systemctl restart postgresql@9.6-main
        - createdb pghero_test
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
