dist: xenial
language: ruby
rvm: 2.6.3
services:
  - postgresql
script: bundle exec rake test
before_install:
  - createdb pghero_test
notifications:
  email:
    on_success: never
    on_failure: change
