dist: bionic
language: ruby
jobs:
  include:
    - rvm: 2.7
      gemfile: Gemfile
    - rvm: 2.6
      gemfile: test/gemfiles/activerecord52.gemfile
    - rvm: 2.5
      gemfile: test/gemfiles/activerecord51.gemfile
    - rvm: 2.4
      gemfile: test/gemfiles/activerecord50.gemfile
services:
  - postgresql
addons:
  postgresql: 10
script: bundle exec rake test
before_install:
  - echo "shared_preload_libraries = 'pg_stat_statements'" | sudo tee -a /etc/postgresql/10/main/postgresql.conf
  - sudo systemctl restart postgresql@10-main
  - createdb pghero_test
notifications:
  email:
    on_success: never
    on_failure: change
