dist: xenial
language: ruby
rvm: 2.5.3
services:
  - postgresql
script: bundle exec rake test
before_install:
  - psql -c 'CREATE DATABASE pghero_test;' -U postgres
notifications:
  email:
    on_success: never
    on_failure: change
