language: ruby
rvm: 2.2
sudo: false
script: bundle exec rake test
before_script:
  - psql -c 'create database pghero_test;' -U postgres
notifications:
  email:
    on_success: never
    on_failure: change
